### ISSUE TITLE
JS Errors

### ISSUE THREAD

**Issue by nickhamze** [sortastupid/woz#10]
I'm seeing some JS errors on the console. Can you figure out what is going wrong?

![js](https://user-images.githubusercontent.com/158918/67243238-bdacf080-f41c-11e9-8e0e-08cc8f8ac60d.png)

**Comment by ariccioppox** [comment]
**ISSUE FIXED**
Added if statement in order to avoid 'Uncaught TypeError' exceptions.
Closing this issue, please reopen if any unexpected JS errors occur.
