### ISSUE TITLE
Scrollbars

### ISSUE THREAD

**Issue by nickhamze** [sortastupid/woz#2]
How come you changed the scrollbar shadow. It use to be chunkier and I really liked it?

![scroll](https://user-images.githubusercontent.com/158918/67026324-23237900-f0cd-11e9-9d59-a866471974be.png)

**Comment by ariccioppox** [comment]
**ISSUE FIXED**
Added box-shadow to scroll bar in order to fix the reported gap.
Closing this issue, please reopen if scroll bar does not display as expected.
