### ISSUE TITLE
Scrollbars on mobile

### ISSUE THREAD

**Issue by nickhamze** [sortastupid/woz#3]
I can't see them on mobile. Scroll works but the bars are so small I can't really use them. I'm using Chrome on my Pixel 3a.

**Comment by ariccioppox** [comment]
**ISSUE FIXED**
Removed mobile scroll bars "width: auto; height: auto;" and added scroll bar thumb "min-height: 25px;". 
Closing this issue, please reopen if the reported behavior persists.
