### ISSUE TITLE
Inner Background image

### ISSUE THREAD

**Issue by nickhamze** [sortastupid/woz#5]
What do you think about converting the inner background image to a linear gradient instead. I'm not super thrilled how it's repeating and I think we could get it to work with just CSS:
https://cssgradient.io/blog/repeating-linear-gradient-css/

**Comment by ariccioppox** [comment]
**ISSUE FIXED**
Changed the inner background image pattern to repeating-linear-gradient.
Closing this issue, please reopen if any background styling enhancement would apply.
