### ISSUE TITLE
Dropdown menu

### ISSUE THREAD

**Issue by nickhamze** [sortastupid/woz#6]
Can we tweak the hover states (add more padding) so it looks a bit more like this?

![dropdown](https://user-images.githubusercontent.com/158918/67027270-e062a080-f0ce-11e9-8065-3ed14b8d63a3.png)

**Comment by ariccioppox** [comment]
**ISSUE FIXED**
Added more padding to menu dropdown label and items.
Closing this issue, please reopen if there are still any styling enhancement you wish to see in dropdowns.
