### ISSUE TITLE
Contact Icon 

### ISSUE THREAD

**Issue by nickhamze** [sortastupid/woz#9]
The contact form link doesn't work. It opens my mail client but doesn't put in the email address. Can you look at that? 

We have the meta field listed twice in the header maybe that's making it mad.

**Comment by ariccioppox** [comment]
**ISSUE FIXED** 594fa131a53ef610df78b52a770c4a5c4e149c54
Apparently, meta tags name string must not have hyphens.
Closing this issue,  please reopen if the reported behavior persists.
